"""Generate RCR-YOLO model yaml variants (YOLO11n width, explicit channels).

Ultralytics parse_model does not width-scale or inject channels for custom
modules, so channel counts are written explicitly for the *n* scale
(P2=64, neck P3=64 / P4=128 / P5=256).  Variants emitted (ablation matrix):

    yolo11n.yaml            -> use stock ultralytics cfg as baseline
    yolo11n-orb.yaml        -> + ORBIn only
    yolo11n-mrfe.yaml       -> + MRFE only
    yolo11n-lcr.yaml        -> + LCR only
    yolo11n-lcrbase.yaml    -> + LCRBase only (fallback)
    yolo11n-rcr.yaml        -> ORBIn + MRFE + LCR   (full RCR-YOLO)
    yolo11n-rcrfb.yaml      -> ORBIn + MRFE + LCRBase (fallback full)
    yolo11n-orbmrfe.yaml    -> ORBIn + MRFE (LCR-free candidate after ablation)
    yolo11n-mrfelcrb.yaml   -> MRFE + LCRBase (pairwise cell: harmonizer generality)
    yolo11n-orblcrb.yaml    -> ORBIn + LCRBase (pairwise cell: completes 2x2x2 grid)

Usage:  python cfg/gen_yaml.py
"""

from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent


def build(orb: bool, neck: str):
    """neck in {'none', 'mrfe', 'lcr', 'lcrbase', 'rcr', 'rcrfb', 'mrfelcrb'}."""
    lcr_mod = {"lcr": "LCR", "lcrbase": "LCRBase", "rcr": "LCR", "rcrfb": "LCRBase", "mrfelcrb": "LCRBase"}.get(neck)
    use_mrfe = neck in {"mrfe", "rcr", "rcrfb", "mrfelcrb"}

    backbone = [
        [-1, 1, "Conv", [16, 3, 2]],            # 0  P1/2
        [-1, 1, "Conv", [32, 3, 2]],            # 1  P2/4
        [-1, 1, "C3k2", [64, False, 0.25]],     # 2
    ]
    if orb:
        backbone.append([-1, 1, "ORBIn", [64, 1, 2]])  # 3  P2 recon (train-only), 2x upsample
    backbone += [
        [-1, 1, "Conv", [64, 3, 2]],            # P3/8
        [-1, 1, "C3k2", [128, False, 0.25]],
        [-1, 1, "Conv", [128, 3, 2]],           # P4/16
        [-1, 1, "C3k2", [128, True]],
        [-1, 1, "Conv", [256, 3, 2]],           # P5/32
        [-1, 1, "C3k2", [256, True]],
        [-1, 1, "SPPF", [256, 5]],
        [-1, 1, "C2PSA", [256]],
    ]

    def neck_scale(ch):
        """MRFE (+LCR) insertion rows at one neck scale."""
        rows = []
        if use_mrfe:
            rows.append([-1, 1, "MRFE", [ch]])
        if lcr_mod:
            rows.append([-1, 1, lcr_mod, [ch]])
        return rows

    head = [
        [-1, 1, "nn.Upsample", [None, 2, "nearest"]],
    ]
    nb = len(backbone)
    # backbone tail: ..., nb-7:C3k2(P3 feat), nb-5:C3k2(P4 feat), nb-1:C2PSA
    p4_bb, p3_bb = nb - 5, nb - 7
    head.append([[-1, p4_bb], 1, "Concat", [1]])
    head.append([-1, 1, "C3k2", [128, False]])   # head P4
    idx_p4 = nb + len(head) - 1
    head.append([-1, 1, "nn.Upsample", [None, 2, "nearest"]])
    head.append([[-1, p3_bb], 1, "Concat", [1]])
    head.append([-1, 1, "C3k2", [64, False]])    # P3 base
    head += neck_scale(64)
    idx_p3_out = nb + len(head) - 1
    head.append([-1, 1, "Conv", [64, 3, 2]])
    head.append([[-1, idx_p4], 1, "Concat", [1]])
    head.append([-1, 1, "C3k2", [128, False]])   # P4 base
    head += neck_scale(128)
    idx_p4_out = nb + len(head) - 1
    head.append([-1, 1, "Conv", [128, 3, 2]])
    head.append([[-1, nb - 1], 1, "Concat", [1]])  # cat C2PSA
    head.append([-1, 1, "C3k2", [256, True]])    # P5 base
    head += neck_scale(256)
    idx_p5_out = nb + len(head) - 1
    head.append([[idx_p3_out, idx_p4_out, idx_p5_out], 1, "Detect", ["nc"]])
    return {"nc": 80, "backbone": backbone, "head": head}


def main():
    variants = {
        "yolo11n-orb.yaml": dict(orb=True, neck="none"),
        "yolo11n-mrfe.yaml": dict(orb=False, neck="mrfe"),
        "yolo11n-lcr.yaml": dict(orb=False, neck="lcr"),
        "yolo11n-lcrbase.yaml": dict(orb=False, neck="lcrbase"),
        "yolo11n-rcr.yaml": dict(orb=True, neck="rcr"),
        "yolo11n-rcrfb.yaml": dict(orb=True, neck="rcrfb"),
        "yolo11n-orbmrfe.yaml": dict(orb=True, neck="mrfe"),
        "yolo11n-mrfelcrb.yaml": dict(orb=False, neck="mrfelcrb"),
        "yolo11n-orblcrb.yaml": dict(orb=True, neck="lcrbase"),
    }
    for name, kw in variants.items():
        spec = build(**kw)
        out = HERE / name
        with open(out, "w", encoding="utf-8") as f:
            f.write(f"# auto-generated by gen_yaml.py : {name}\n")
            yaml.dump(spec, f, default_flow_style=None, sort_keys=False)
        print("wrote", out)


if __name__ == "__main__":
    main()
